import 'package:flutter/material.dart';

/// The category/type of an adaptive shortcut generated from commuter usage.
enum AdaptiveShortcutType {
  route,
  liveTracking,
  ticketBooking,
  savedPlace,
  corridorAlerts,
  safety,
  feature,
}

/// The commuter's governance status for an adaptive shortcut.
enum AdaptiveShortcutStatus {
  /// Generated by usage pattern analysis, awaiting commuter review.
  suggested,

  /// Explicitly accepted/pinned by the commuter.
  accepted,

  /// Explicitly dismissed/rejected by the commuter.
  dismissed,
}

/// An adaptive shortcut generated dynamically by analyzing non-sensitive commuting habits.
class AdaptiveShortcut {
  const AdaptiveShortcut({
    required this.id,
    required this.type,
    required this.title,
    required this.subtitle,
    required this.actionType,
    this.actionData = const {},
    this.usageCount = 1,
    required this.lastUsed,
    this.status = AdaptiveShortcutStatus.suggested,
    this.customIcon,
    this.customColor,
  });

  /// Unique identifier for this shortcut pattern.
  final String id;

  /// Semantic type of the shortcut.
  final AdaptiveShortcutType type;

  /// Primary label displayed on the shortcut card or chip.
  final String title;

  /// Contextual subtitle explaining why the shortcut is suggested (e.g. "Used 3 times").
  final String subtitle;

  /// The action identifier executed when the shortcut is tapped.
  final String actionType;

  /// Arguments required to execute the action (e.g. originId, destinationId, busId).
  final Map<String, dynamic> actionData;

  /// Frequency count of how often this action pattern has been triggered.
  final int usageCount;

  /// Timestamp when this pattern was most recently triggered.
  final DateTime lastUsed;

  /// User governance state (suggested, accepted, dismissed).
  final AdaptiveShortcutStatus status;

  /// Optional icon override.
  final IconData? customIcon;

  /// Optional color override.
  final Color? customColor;

  bool get isAccepted => status == AdaptiveShortcutStatus.accepted;
  bool get isSuggested => status == AdaptiveShortcutStatus.suggested;
  bool get isDismissed => status == AdaptiveShortcutStatus.dismissed;

  /// Primary icon representing the action.
  IconData get icon {
    if (customIcon != null) return customIcon!;
    switch (type) {
      case AdaptiveShortcutType.route:
        return Icons.alt_route_rounded;
      case AdaptiveShortcutType.liveTracking:
        return Icons.my_location_rounded;
      case AdaptiveShortcutType.ticketBooking:
        return Icons.confirmation_number_outlined;
      case AdaptiveShortcutType.savedPlace:
        return Icons.star_rounded;
      case AdaptiveShortcutType.corridorAlerts:
        return Icons.notifications_active_outlined;
      case AdaptiveShortcutType.safety:
        return Icons.health_and_safety_outlined;
      case AdaptiveShortcutType.feature:
        return Icons.bolt_rounded;
    }
  }

  /// Theme accent color.
  Color get color {
    if (customColor != null) return customColor!;
    switch (type) {
      case AdaptiveShortcutType.route:
        return const Color(0xFF0284C7); // Sky Blue
      case AdaptiveShortcutType.liveTracking:
        return const Color(0xFF16A34A); // Emerald Green
      case AdaptiveShortcutType.ticketBooking:
        return const Color(0xFF7C3AED); // Vibrant Purple
      case AdaptiveShortcutType.savedPlace:
        return const Color(0xFFEA580C); // Orange
      case AdaptiveShortcutType.corridorAlerts:
        return const Color(0xFFD97706); // Amber
      case AdaptiveShortcutType.safety:
        return const Color(0xFFE11D48); // Rose
      case AdaptiveShortcutType.feature:
        return const Color(0xFF007AFF); // Electric Blue
    }
  }

  /// Returns a copy of the shortcut with modified parameters.
  AdaptiveShortcut copyWith({
    String? id,
    AdaptiveShortcutType? type,
    String? title,
    String? subtitle,
    String? actionType,
    Map<String, dynamic>? actionData,
    int? usageCount,
    DateTime? lastUsed,
    AdaptiveShortcutStatus? status,
    IconData? customIcon,
    Color? customColor,
  }) {
    return AdaptiveShortcut(
      id: id ?? this.id,
      type: type ?? this.type,
      title: title ?? this.title,
      subtitle: subtitle ?? this.subtitle,
      actionType: actionType ?? this.actionType,
      actionData: actionData ?? this.actionData,
      usageCount: usageCount ?? this.usageCount,
      lastUsed: lastUsed ?? this.lastUsed,
      status: status ?? this.status,
      customIcon: customIcon ?? this.customIcon,
      customColor: customColor ?? this.customColor,
    );
  }

  /// Serializes shortcut to a JSON-compatible map.
  Map<String, dynamic> toJson() => {
        'id': id,
        'type': type.name,
        'title': title,
        'subtitle': subtitle,
        'actionType': actionType,
        'actionData': actionData,
        'usageCount': usageCount,
        'lastUsed': lastUsed.toIso8601String(),
        'status': status.name,
      };

  /// Constructs shortcut from a JSON map.
  factory AdaptiveShortcut.fromJson(Map<String, dynamic> json) {
    return AdaptiveShortcut(
      id: json['id'] as String? ?? 'shortcut_${DateTime.now().millisecondsSinceEpoch}',
      type: AdaptiveShortcutType.values.firstWhere(
        (e) => e.name == json['type'],
        orElse: () => AdaptiveShortcutType.route,
      ),
      title: json['title'] as String? ?? 'Suggested Shortcut',
      subtitle: json['subtitle'] as String? ?? '',
      actionType: json['actionType'] as String? ?? 'route_search',
      actionData: (json['actionData'] as Map<String, dynamic>?) ?? {},
      usageCount: json['usageCount'] as int? ?? 1,
      lastUsed: DateTime.tryParse(json['lastUsed'] as String? ?? '') ?? DateTime.now(),
      status: AdaptiveShortcutStatus.values.firstWhere(
        (e) => e.name == json['status'],
        orElse: () => AdaptiveShortcutStatus.suggested,
      ),
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdaptiveShortcut &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          type == other.type &&
          title == other.title &&
          status == other.status;

  @override
  int get hashCode => id.hashCode ^ type.hashCode ^ title.hashCode ^ status.hashCode;

  @override
  String toString() => 'AdaptiveShortcut(id: $id, title: $title, status: ${status.name}, count: $usageCount)';
}
